/// Flutter icons Figmaicon
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Figmaicon
///      fonts:
///       - asset: fonts/Figmaicon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class FigmaIcon {
  FigmaIcon._();

  static const _kFontFam = 'Figmaicon';
  static const String? _kFontPkg = null;

  static const IconData uploadIcon = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
