/// Flutter icons Figmauploadicon
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Figmauploadicon
///      fonts:
///       - asset: fonts/Figmauploadicon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Figmauploadicon {
  Figmauploadicon._();

  static const _kFontFam = 'Figmauploadicon';
  static const String? _kFontPkg = null;

  static const IconData group_1 = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData group_5420 = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData group_5412 = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow___down = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rocket = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vector = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vector1 = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData backButton = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData privacypolicy3 = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData privacypolicy2 = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData privacypolicy1 = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);

}
